### ISSUE TITLE
A small change

### ISSUE THREAD

**Issue by nevesanjos** [andreavb/TWICTools#1]
In order to work on my system (linux/Debian), I changed the line:
import urllib

to:
import urllib.request

and every time "urllib" appears I included ".request" next to it.  

Thanks,
Felipe

**Comment by andreavb** [comment]
Hey, Felipe, thanks for commenting!

From the fix you found out, I believe you are running Python 3, is my assumption correct? If yes, I just committed 881b3a4 based on your observations.

Please let me know if that helps!
Andrea

**Comment by nevesanjos** [comment]
Hey @andreavb 

Yes, that is correct, I am using Python 3. I made the "git pull" and it is working. Thank you. 

Felipe
